name: L2 Motion Integration Installer
version: "1.0.7"
slug: l2_motion_installer
description: Installs or updates the L2 Motion Bed custom integration.
url: https://github.com/Franklin-C/l2-motion-home-assistant
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: once
boot: manual
init: false
map:
  - type: homeassistant_config
    read_only: false
options: {}
schema: {}
